---
ID: "c3ae1917-9885-4bfa-81a0-485fdac2014a"
Parent: "3228313e-325f-4adf-afd3-b16c5c3da60d"
Template: "3228313e-325f-4adf-afd3-b16c5c3da60d"
Path: /sitecore/templates/Feature/SUGCON/General/Custom Content Block/Custom Content Block Params/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230914T003859Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "dcecf94c-4e76-4a03-a785-9903184155d2"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230914T003859Z
