---
ID: "831522dc-e676-4817-8298-2e07125f06f3"
Parent: "10138cf5-9ac5-4992-95a6-23a9b4cc98b0"
Template: "10138cf5-9ac5-4992-95a6-23a9b4cc98b0"
Path: /sitecore/templates/Feature/SUGCON/Listing/Card Listing/Card Listing/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{DBAEEFBE-0C61-423B-BA96-98B58614C2A2}"
Languages:
- Language: en
  Fields:
  - ID: "9541e67d-ce8c-4225-803d-33f7f29f09ef"
    Hint: __Short description
    Value: Insert child items to add cards
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230828T152835Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "639981f4-6eb4-4f0c-b309-50476ee79b3e"
      Hint: headline
      Value: $name
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1916759f-9150-4afa-8c24-d230bd08c92d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230828T222956Z
