
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// eslint-disable-next-line @typescript-eslint/no-unused-vars 
import { ItemExt } from '../lib/_.Sitecore.Override'
// eslint-disable-next-line @typescript-eslint/no-unused-vars 
import { Field, ImageField, FileField, LinkField } from '@sitecore-jss/sitecore-jss-nextjs';
// eslint-disable-next-line @typescript-eslint/no-unused-vars 
import { ComponentProps } from '../lib/component-props';
import { Foundation } from "./Foundation.JssExperienceAccelerator.model"

export namespace Feature.JssExperienceAccelerator.PageStructure.RenderingParameters {
    export type Container = 
        Foundation.JssExperienceAccelerator.Presentation.RenderingParameters.BaseRenderingParameters & {
        fields?: { 
            /**
            * Represents the Background image field (6845679d-e298-4e94-96eb-230cb7c3baae).
            */
            BackgroundImage: ImageField;
        }

    }
}
export namespace Feature.JssExperienceAccelerator.Media {
    export type Image = {
        fields?: { 
            /**
            * Represents the Image field (57caf172-ce57-4e48-b3a1-46f8aea71c08).
            */
            Image: ImageField;

            /**
            * Represents the Caption field (4d7b05d0-0300-486f-8f87-57de34a9b793).
            */
            ImageCaption: Field<string>;

            /**
            * Represents the URL field (75fbf1b1-e7c5-494b-9633-693909f79425).
            */
            TargetUrl: LinkField;
        }

    }
}
export namespace Feature.JssExperienceAccelerator.Media.RenderingParameters {
    export type Image = 
        Foundation.JssExperienceAccelerator.Presentation.RenderingParameters.BaseRenderingParameters & {
        fields?: {         }

    }
}
export namespace Feature.JssExperienceAccelerator.Media {
    export type ImageFolder = {
        fields?: {         }

    }
}
export namespace Feature.JssExperienceAccelerator.Navigation.Datasource {
    export type Link = {
        fields?: { 
            /**
            * Represents the Link field (68c2a603-f98e-42a3-be2d-dd70598c2a63).
            */
            Link: LinkField;
        }

    }
    export type LinkList = {
        fields?: { 
            /**
            * Represents the Title field (dc9aaee9-fc44-458d-a9fb-bac61d8b0234).
            */
            Title: Field<string>;
        }

    }
    export type LinkListFolder = {
        fields?: {         }

    }
}
export namespace Feature.JssExperienceAccelerator.Navigation.RenderingParameters {
    export type LinkList = 
        Foundation.JssExperienceAccelerator.Presentation.RenderingParameters.BaseRenderingParameters & {
        fields?: {         }

    }
    export type Navigation = 
        Foundation.JssExperienceAccelerator.Presentation.RenderingParameters.BaseRenderingParameters & {
        fields?: {         }

    }
}
export namespace Feature.JssExperienceAccelerator.PageContent.RenderingParameters {
    export type PageContent = 
        Foundation.JssExperienceAccelerator.Presentation.RenderingParameters.BaseRenderingParameters & {
        fields?: {         }

    }
}
export namespace Feature.JssExperienceAccelerator.PageContent {
    export type Promo = {
        fields?: { 
            /**
            * Represents the Image field (f94b9858-c439-4291-863b-757b536c8b65).
            */
            PromoIcon: ImageField;

            /**
            * Represents the Image 2 field (739c6cc2-0031-463d-9599-13478fd50ee3).
            */
            PromoIcon2: ImageField;

            /**
            * Represents the Link field (ef24bed2-46ab-4d53-ad1a-1019935a4e89).
            */
            PromoLink: LinkField;

            /**
            * Represents the Text field (28079f3a-896b-4273-be5f-59d0ebb7cd7d).
            */
            PromoText: Field<string>;

            /**
            * Represents the Text 2 field (1f66862d-a5e3-405f-8e3e-b787b4c39b12).
            */
            PromoText2: Field<string>;

            /**
            * Represents the Text 3 field (c6e604c3-5371-4e67-83df-a09a5ea66249).
            */
            PromoText3: Field<string>;
        }

    }
}
export namespace Feature.JssExperienceAccelerator.PageContent.RenderingParameters {
    export type Promo = 
        Foundation.JssExperienceAccelerator.Presentation.RenderingParameters.BaseRenderingParameters & {
        fields?: {         }

    }
}
export namespace Feature.JssExperienceAccelerator.PageContent {
    export type PromoFolder = {
        fields?: {         }

    }
}
export namespace Feature.JssExperienceAccelerator.PageContent.RenderingParameters {
    export type RichText = 
        Foundation.JssExperienceAccelerator.Presentation.RenderingParameters.BaseRenderingParameters & {
        fields?: {         }

    }
}
export namespace Feature.JssExperienceAccelerator.PageContent {
    export type Text = {
        fields?: { 
            /**
            * Represents the Text field (729034fc-24f3-40b7-8fa4-fb49d7de20dd).
            */
            Text: Field<string>;
        }

    }
    export type TextFolder = {
        fields?: {         }

    }
}
export namespace Feature.JssExperienceAccelerator.PageContent.RenderingParameters {
    export type Title = 
        Foundation.JssExperienceAccelerator.Presentation.RenderingParameters.BaseRenderingParameters & {
        fields?: {         }

    }
}
// Namespace aliases.  If this doesn't work, ensure `"isolatedModules": false` is set in `tsconfig.json`. 
export import PageStructure = Feature.JssExperienceAccelerator.PageStructure;
export import Media = Feature.JssExperienceAccelerator.Media;
export import Navigation = Feature.JssExperienceAccelerator.Navigation;
export import PageContent = Feature.JssExperienceAccelerator.PageContent;


