
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-jss/sitecore-jss-nextjs';
// @ts-ignore 
import { ComponentProps } from '../lib/component-props';
// @ts-ignore 
import { Listing as FeatureSugconListing } from "./Feature.Sugcon.model"
// @ts-ignore 
import { Utility as FoundationSugconUtility } from "./Foundation.Sugcon.model"
// @ts-ignore 
import { Presentation as FoundationJssExperienceAcceleratorPresentation } from "./Foundation.JssExperienceAccelerator.model"
// @ts-ignore 
import { General as FeatureSugconGeneral } from "./Feature.Sugcon.model"

export namespace Listing.CardListing {

    /**
    * Represents the template /sitecore/templates/Feature/SUGCON/Listing/Card Listing/Card Item
    */
    export type CardItem =  {
        fields?: { 
            /**
            * Represents the CTA field (7a5b4674-7a28-42fe-8f8e-e86c5dcbd049).
            */
            cta?: LinkField;

            /**
            * Represents the Headline field (9cafa07d-4fdb-4741-90da-f7b1392458c8).
            */
            headline?: Field<string>;

            /**
            * Represents the Image field (af087590-b739-434a-b9c2-954bd816ae59).
            */
            image?: ImageField;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/SUGCON/Listing/Card Listing/Card Item
    */
    export type CardItemJson =  {
        
            /**
            * Represents the CTA field (7a5b4674-7a28-42fe-8f8e-e86c5dcbd049).
            */
            cta?: {
                jsonValue: LinkField
            };

            /**
            * Represents the Headline field (9cafa07d-4fdb-4741-90da-f7b1392458c8).
            */
            headline?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Image field (af087590-b739-434a-b9c2-954bd816ae59).
            */
            image?: {
                jsonValue: ImageField
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/SUGCON/Listing/Card Listing/Card Listing
    */
    export type CardListing = FoundationSugconUtility.RenderWithChildren &  {
        fields?: { 
            /**
            * Represents the Headline field (639981f4-6eb4-4f0c-b309-50476ee79b3e).
            */
            headline?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/SUGCON/Listing/Card Listing/Card Listing
    */
    export type CardListingJson = FoundationSugconUtility.RenderWithChildrenJson &  {
        
            /**
            * Represents the Headline field (639981f4-6eb4-4f0c-b309-50476ee79b3e).
            */
            headline?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/SUGCON/Listing/Card Listing/Card Listing Params
    */
    export type CardListingParams = FoundationJssExperienceAcceleratorPresentation.RenderingParameters.BaseRenderingParameters &  {
        fields?: { 
            /**
            * Represents the Cards Per Row field (e3688fd5-09ab-4913-963e-1d9d6ef7d86c).
            */
            cardsPerRow?: Field<number>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/SUGCON/Listing/Card Listing/Card Listing Params
    */
    export type CardListingParamsJson = FoundationJssExperienceAcceleratorPresentation.RenderingParameters.BaseRenderingParametersJson &  {
        
            /**
            * Represents the Cards Per Row field (e3688fd5-09ab-4913-963e-1d9d6ef7d86c).
            */
            cardsPerRow?: {
                jsonValue: Field<number>
            };


    }
}
export namespace General.CustomContentBlock {

    /**
    * Represents the template /sitecore/templates/Feature/SUGCON/General/Custom Content Block/Custom Content Block
    */
    export type CustomContentBlock =  {
        fields?: { 
            /**
            * Represents the Content field (071c1b0a-c007-4db9-8c80-59142a7b98ec).
            */
            content?: Field<string>;

            /**
            * Represents the CTA field (5f226afd-df82-425b-9f57-8c3db9b6f488).
            */
            cta?: LinkField;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/SUGCON/General/Custom Content Block/Custom Content Block
    */
    export type CustomContentBlockJson =  {
        
            /**
            * Represents the Content field (071c1b0a-c007-4db9-8c80-59142a7b98ec).
            */
            content?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the CTA field (5f226afd-df82-425b-9f57-8c3db9b6f488).
            */
            cta?: {
                jsonValue: LinkField
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/SUGCON/General/Custom Content Block/Custom Content Block Params
    */
    export type CustomContentBlockParams = FoundationJssExperienceAcceleratorPresentation.RenderingParameters.BaseRenderingParameters &  {
        fields?: { 
            /**
            * Represents the testDate field (2a1145ff-4e62-4569-89c4-3ab23029bd17).
            */
            testDate?: Field<string>;

            /**
            * Represents the testImage field (afe4ec52-a73b-4b07-ba75-d52e3d9ee891).
            */
            testImage?: ImageField;

            /**
            * Represents the testLink field (1eb6afe8-b764-4d5c-979a-27c1d5b4583c).
            */
            testLink?: LinkField;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/SUGCON/General/Custom Content Block/Custom Content Block Params
    */
    export type CustomContentBlockParamsJson = FoundationJssExperienceAcceleratorPresentation.RenderingParameters.BaseRenderingParametersJson &  {
        
            /**
            * Represents the testDate field (2a1145ff-4e62-4569-89c4-3ab23029bd17).
            */
            testDate?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the testImage field (afe4ec52-a73b-4b07-ba75-d52e3d9ee891).
            */
            testImage?: {
                jsonValue: ImageField
            };

            /**
            * Represents the testLink field (1eb6afe8-b764-4d5c-979a-27c1d5b4583c).
            */
            testLink?: {
                jsonValue: LinkField
            };


    }
}
export namespace Listing.PageListing {

    /**
    * Represents the template /sitecore/templates/Feature/SUGCON/Listing/Page Listing/Page Listing
    */
    export type PageListing =  {
        fields?: { 
            /**
            * Represents the levels field (ce387c4e-2018-4d19-ba73-d043825b0f74).
            */
            levels?: Field<number>;

            /**
            * Represents the Root Page field (e74c3459-d157-4210-ad64-978d04a5fa3f).
            */
            rootPage?: Item;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/SUGCON/Listing/Page Listing/Page Listing
    */
    export type PageListingJson =  {
        
            /**
            * Represents the levels field (ce387c4e-2018-4d19-ba73-d043825b0f74).
            */
            levels?: {
                jsonValue: Field<number>
            };

            /**
            * Represents the Root Page field (e74c3459-d157-4210-ad64-978d04a5fa3f).
            */
            rootPage?: {
                jsonValue: Item
            };


    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace Listing.CardListing.Constants {

    export const CardItem = {
        TemplateId: "dbaeefbe-0c61-423b-ba96-98b58614c2a2",
    
        BaseTemplateIds: [
        ]
    }
    export const CardListing = {
        TemplateId: "10138cf5-9ac5-4992-95a6-23a9b4cc98b0",
    
        BaseTemplateIds: [
            "75848221-862f-48ed-83d1-af13ed1c2cd7", 
        ]
    }
    export const CardListingParams = {
        TemplateId: "2f4b70d0-231d-4b39-9b6b-f4d82f6ef4ae",
    
        BaseTemplateIds: [
            "4247aad4-ebde-4994-998f-e067a51b1fe4", 
        ]
    }
}
export namespace General.CustomContentBlock.Constants {

    export const CustomContentBlock = {
        TemplateId: "2b9cadf2-a466-44af-909f-d49d10c57bf5",
    
        BaseTemplateIds: [
        ]
    }
    export const CustomContentBlockParams = {
        TemplateId: "3228313e-325f-4adf-afd3-b16c5c3da60d",
    
        BaseTemplateIds: [
            "4247aad4-ebde-4994-998f-e067a51b1fe4", 
        ]
    }
}
export namespace Listing.PageListing.Constants {

    export const PageListing = {
        TemplateId: "424a1312-e34e-44ea-af8d-0910572efdac",
    
        BaseTemplateIds: [
        ]
    }
}    


