
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { ItemExt } from '../lib/_.Sitecore.Override'
// @ts-ignore 
import { Field, ImageField, FileField, LinkField } from '@sitecore-jss/sitecore-jss-nextjs';
// @ts-ignore 
import { ComponentProps } from '../lib/component-props';
// @ts-ignore 
import { Scaffolding as FoundationJssExperienceAcceleratorScaffolding } from "./Foundation.JssExperienceAccelerator.model"
// @ts-ignore 
import { Presentation as FoundationJssExperienceAcceleratorPresentation } from "./Foundation.JssExperienceAccelerator.model"
// @ts-ignore 
import { Multisite as FoundationJssExperienceAcceleratorMultisite } from "./Foundation.JssExperienceAccelerator.model"
// @ts-ignore 
import { HeadlessVariants as FoundationJssExperienceAcceleratorHeadlessVariants } from "./Foundation.JssExperienceAccelerator.model"
// @ts-ignore 
import { PlaceholderSettings as FoundationJssExperienceAcceleratorPlaceholderSettings } from "./Foundation.JssExperienceAccelerator.model"
// @ts-ignore 
import { SiteMetadata as FoundationJssExperienceAcceleratorSiteMetadata } from "./Foundation.JssExperienceAccelerator.model"

export namespace Scaffolding.Actions.Site {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Actions/Site/AddItem
    */
    export type AddItem =  {
        fields?: { 
            /**
            * Represents the Location field (52c91c75-6698-4701-a8a2-242ace59a8d6).
            */
            Location?: ItemExt[];
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Actions/Site/AddItem
    */
    export type AddItemJson =  {
        
            /**
            * Represents the Location field (52c91c75-6698-4701-a8a2-242ace59a8d6).
            */
            Location?: {
                jsonValue: ItemExt[]
            };


    }
}
export namespace Scaffolding.Actions.Tenant {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Actions/Tenant/AddItem
    */
    export type AddItem =  {
        fields?: { 
            /**
            * Represents the Location field (49ed6c70-37bd-4a23-af04-209806605b7f).
            */
            Location?: ItemExt[];
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Actions/Tenant/AddItem
    */
    export type AddItemJson =  {
        
            /**
            * Represents the Location field (49ed6c70-37bd-4a23-af04-209806605b7f).
            */
            Location?: {
                jsonValue: ItemExt[]
            };


    }
}
export namespace Presentation.AvailableRenderings {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Presentation/Available Renderings/Available Renderings Folder
    */
    export type AvailableRenderingsFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Presentation/Available Renderings/Available Renderings Folder
    */
    export type AvailableRenderingsFolderJson =  {
        

    }
}
export namespace Multisite {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Multisite/Base Page
    */
    export type BasePage =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Multisite/Base Page
    */
    export type BasePageJson =  {
        

    }
}
export namespace Presentation.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Presentation/Rendering Parameters/BaseRenderingParameters
    */
    export type BaseRenderingParameters =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Presentation/Rendering Parameters/BaseRenderingParameters
    */
    export type BaseRenderingParametersJson =  {
        

    }
}
export namespace Scaffolding.Actions.Site {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Actions/Site/EditSiteItem
    */
    export type EditSiteItem =  {
        fields?: { 
            /**
            * Represents the Template field (0916832d-459e-463c-852b-c538476a422d).
            */
            Template?: ItemExt[];
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Actions/Site/EditSiteItem
    */
    export type EditSiteItemJson =  {
        
            /**
            * Represents the Template field (0916832d-459e-463c-852b-c538476a422d).
            */
            Template?: {
                jsonValue: ItemExt[]
            };


    }
}
export namespace Scaffolding.Actions.Tenant {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Actions/Tenant/EditTenantTemplate
    */
    export type EditTenantTemplate =  {
        fields?: { 
            /**
            * Represents the Template field (67b6641e-309d-4c1e-8e97-63965c7e2c5f).
            */
            Template?: ItemExt[];
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Actions/Tenant/EditTenantTemplate
    */
    export type EditTenantTemplateJson =  {
        
            /**
            * Represents the Template field (67b6641e-309d-4c1e-8e97-63965c7e2c5f).
            */
            Template?: {
                jsonValue: ItemExt[]
            };


    }
}
export namespace Scaffolding.Actions.Site {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Actions/Site/ExecuteScript
    */
    export type ExecuteScript =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Actions/Site/ExecuteScript
    */
    export type ExecuteScriptJson =  {
        

    }
}
export namespace Scaffolding.Actions.Tenant {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Actions/Tenant/ExecuteScript
    */
    export type ExecuteScript =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Actions/Tenant/ExecuteScript
    */
    export type ExecuteScriptJson =  {
        

    }
}
export namespace Multisite {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Multisite/Headless Site
    */
    export type HeadlessSite =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Multisite/Headless Site
    */
    export type HeadlessSiteJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Multisite/Headless Tenant
    */
    export type HeadlessTenant = FoundationJssExperienceAcceleratorMultisite.Base.BaseJssTenant &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Multisite/Headless Tenant
    */
    export type HeadlessTenantJson = FoundationJssExperienceAcceleratorMultisite.Base.BaseJssTenantJson &  {
        

    }
}
export namespace Scaffolding.Roots {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Roots/HeadlessSiteSetupRoot
    */
    export type HeadlessSiteSetupRoot =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Roots/HeadlessSiteSetupRoot
    */
    export type HeadlessSiteSetupRootJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Roots/HeadlessTenantSetupRoot
    */
    export type HeadlessTenantSetupRoot =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Roots/HeadlessTenantSetupRoot
    */
    export type HeadlessTenantSetupRootJson =  {
        

    }
}
export namespace HeadlessVariants {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Headless Variants/HeadlessVariants
    */
    export type HeadlessVariants =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Headless Variants/HeadlessVariants
    */
    export type HeadlessVariantsJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Headless Variants/HeadlessVariantsGrouping
    */
    export type HeadlessVariantsGrouping =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Headless Variants/HeadlessVariantsGrouping
    */
    export type HeadlessVariantsGroupingJson =  {
        

    }
}
export namespace Scaffolding.Actions.Site {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Actions/Site/InputValidationStep
    */
    export type InputValidationStep =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Actions/Site/InputValidationStep
    */
    export type InputValidationStepJson =  {
        

    }
}
export namespace Scaffolding.Actions.Tenant {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Actions/Tenant/InputValidationStep
    */
    export type InputValidationStep =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Actions/Tenant/InputValidationStep
    */
    export type InputValidationStepJson =  {
        

    }
}
export namespace Multisite {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Multisite/JSS Data
    */
    export type JssData =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Multisite/JSS Data
    */
    export type JssDataJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Multisite/JSS Settings
    */
    export type JssSettings =  {
        fields?: { 
            /**
            * Represents the Analyze allowed controls field (812dedeb-c5bd-471c-9f48-b1ce75d0d4a9).
            */
            AnalyzeAllowedControls?: Field<boolean>;

            /**
            * Represents the App data sources path field (5764d2d4-724d-4313-a81b-9246c911faff).
            */
            AppDatasourcesPath?: ItemExt;

            /**
            * Represents the App template field (32ce6bbe-4217-46e5-9335-42793884cbe3).
            */
            AppTemplate?: ItemExt;

            /**
            * Represents the Datasource strategy field (f7c6acfb-63f0-4aca-9e44-3133b2b94a5b).
            */
            DatasourceStrategy?: Field<string>;

            /**
            * Represents the Debug security field (a5c4b74e-993a-40d6-aeab-23bb12abcf0a).
            */
            DebugSecurity?: Field<boolean>;

            /**
            * Represents the Default workflow field (3af0e329-6d5e-4d8f-9f82-f48265658a3e).
            */
            DefaultWorkflow?: ItemExt;

            /**
            * Represents the Deployment secret field (797d2f63-d5c4-4c4c-b21f-d3e250e2ab12).
            */
            DeploymentSecret?: Field<string>;

            /**
            * Represents the Dictionary domain field (0129da3f-8c86-4591-ae32-6ec923413923).
            */
            DictionaryDomain?: ItemExt;

            /**
            * Represents the Dictionary path field (a7bbad73-b933-49ff-95c8-1c269cb35e7c).
            */
            DictionaryPath?: ItemExt;

            /**
            * Represents the Filesystem path field (72e83c8d-3578-4e50-b4c0-93a78a1729f2).
            */
            FilesystemPath?: Field<string>;

            /**
            * Represents the Folder template field (bde120a5-4cc2-4340-9b63-562a139bf197).
            */
            FolderTemplate?: ItemExt;

            /**
            * Represents the GraphQL endpoint field (30e0a829-637e-478c-a136-66adb568398d).
            */
            GraphQLEndpoint?: Field<string>;

            /**
            * Represents the Import database field (df376030-46e9-4c77-bc05-debefc86e3d5).
            */
            ImportDatabase?: Field<string>;

            /**
            * Represents the Import device field (1f14aa04-2868-481f-9247-30dc5c65672c).
            */
            ImportDevice?: ItemExt;

            /**
            * Represents the Import language field (04e6b1f3-ae47-4d95-a154-2271075869a9).
            */
            ImportLanguage?: Field<string>;

            /**
            * Represents the Import user field (f87f0d81-c32c-4c1d-8caf-67856c3ab06e).
            */
            ImportUser?: Field<string>;

            /**
            * Represents the Layout folder template field (466902a9-6b16-41b1-9d33-7c55094a2713).
            */
            LayoutFolderTemplate?: ItemExt;

            /**
            * Represents the Layout path field (c8d002f9-9518-4c5e-9baa-6617e13f0797).
            */
            LayoutPath?: ItemExt;

            /**
            * Represents the Layout service configuration field (e3259313-387a-41f0-b113-962f14b1aa2b).
            */
            LayoutServiceConfiguration?: Field<string>;

            /**
            * Represents the Layout template field (e13c1a83-9d60-4530-b318-3a5effcc6338).
            */
            LayoutTemplate?: ItemExt;

            /**
            * Represents the Media Library folder template field (1cc82067-2b48-442a-a352-453d56a49d93).
            */
            MediaLibraryFolderTemplate?: ItemExt;

            /**
            * Represents the App Name field (3e4f559f-8e59-4405-b50d-619811371f6c).
            */
            Name?: Field<string>;

            /**
            * Represents the Optimize import indexing field (4088f63e-09e5-43fa-ae99-829bd9bdc114).
            */
            OptimizeImportIndexing?: Field<boolean>;

            /**
            * Represents the Placeholder settings folder template field (f5594251-f757-429e-a9bd-07f65f6875b9).
            */
            PlaceholderSettingsFolderTemplate?: ItemExt;

            /**
            * Represents the Placeholders path field (5ca117eb-8782-4a4f-9f2f-30de31fc2e34).
            */
            PlaceholdersPath?: ItemExt;

            /**
            * Represents the Protect developer items field (b0711df7-724a-4c6c-8d4d-be846de6124c).
            */
            ProtectDeveloperItems?: Field<boolean>;

            /**
            * Represents the Renderings folder template field (f5821c4c-226e-4953-8213-c0243826f85f).
            */
            RenderingsFolderTemplate?: ItemExt;

            /**
            * Represents the Renderings path field (f29428d5-1285-48b8-a884-44057965829a).
            */
            RenderingsPath?: ItemExt;

            /**
            * Represents the Route base template field (396af2f6-fe48-4fd4-a7e2-3da13ef977eb).
            */
            RouteBaseTemplate?: ItemExt;

            /**
            * Represents the Route data sources path field (414f61dd-02c2-47d1-ba83-dcfbc3071e52).
            */
            RouteDatasourcesPath?: Field<string>;

            /**
            * Represents the Route template name field (300fb7a0-b27f-44dd-9af0-b37a19723e0e).
            */
            RouteTemplateName?: Field<string>;

            /**
            * Represents the Server Bundle field (4a3eeba3-a250-44f4-bd97-6e863cc6f0d5).
            */
            ServerBundle?: Field<string>;

            /**
            * Represents the Server side rendering engine field (9016141c-ff51-40f2-9135-40f5161b9784).
            */
            ServerSideRenderingEngine?: Field<string>;

            /**
            * Represents the ServerSideRenderingEngineApplicationUrl field (5e8ed724-126a-4bb7-8106-85c2d1042c9e).
            */
            ServerSideRenderingEngineApplicationUrl?: Field<string>;

            /**
            * Represents the ServerSideRenderingEngineEditOnly field (557d5f36-6f2d-4eb6-a8ce-25f30f7b9397).
            */
            ServerSideRenderingEngineEditOnly?: Field<boolean>;

            /**
            * Represents the Server side rendering engine endpoint URL field (89849738-34ee-46bc-b525-825f1153189e).
            */
            ServerSideRenderingEngineEndpointUrl?: Field<string>;

            /**
            * Represents the Server side rendering function name field (7975673a-aafd-4c5b-96a5-cbcaac500a44).
            */
            ServerSideRenderingFunctionName?: Field<string>;

            /**
            * Represents the Server side rendering worker processes field (6224a1ce-d964-4ee8-8e09-ad2f81e0a2b6).
            */
            ServerSideRenderingWorkerProcesses?: Field<number>;

            /**
            * Represents the Template folder template field (218760c0-8001-4c2d-a8b0-61c128276f96).
            */
            TemplateFolderTemplate?: ItemExt;

            /**
            * Represents the Use language specific layout field (1864e99d-c29a-40bf-96e0-b3e7896a013b).
            */
            UseLanguageSpecificLayout?: Field<boolean>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Multisite/JSS Settings
    */
    export type JssSettingsJson =  {
        
            /**
            * Represents the Analyze allowed controls field (812dedeb-c5bd-471c-9f48-b1ce75d0d4a9).
            */
            AnalyzeAllowedControls?: {
                jsonValue: Field<boolean>
            };

            /**
            * Represents the App data sources path field (5764d2d4-724d-4313-a81b-9246c911faff).
            */
            AppDatasourcesPath?: {
                jsonValue: ItemExt
            };

            /**
            * Represents the App template field (32ce6bbe-4217-46e5-9335-42793884cbe3).
            */
            AppTemplate?: {
                jsonValue: ItemExt
            };

            /**
            * Represents the Datasource strategy field (f7c6acfb-63f0-4aca-9e44-3133b2b94a5b).
            */
            DatasourceStrategy?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Debug security field (a5c4b74e-993a-40d6-aeab-23bb12abcf0a).
            */
            DebugSecurity?: {
                jsonValue: Field<boolean>
            };

            /**
            * Represents the Default workflow field (3af0e329-6d5e-4d8f-9f82-f48265658a3e).
            */
            DefaultWorkflow?: {
                jsonValue: ItemExt
            };

            /**
            * Represents the Deployment secret field (797d2f63-d5c4-4c4c-b21f-d3e250e2ab12).
            */
            DeploymentSecret?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Dictionary domain field (0129da3f-8c86-4591-ae32-6ec923413923).
            */
            DictionaryDomain?: {
                jsonValue: ItemExt
            };

            /**
            * Represents the Dictionary path field (a7bbad73-b933-49ff-95c8-1c269cb35e7c).
            */
            DictionaryPath?: {
                jsonValue: ItemExt
            };

            /**
            * Represents the Filesystem path field (72e83c8d-3578-4e50-b4c0-93a78a1729f2).
            */
            FilesystemPath?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Folder template field (bde120a5-4cc2-4340-9b63-562a139bf197).
            */
            FolderTemplate?: {
                jsonValue: ItemExt
            };

            /**
            * Represents the GraphQL endpoint field (30e0a829-637e-478c-a136-66adb568398d).
            */
            GraphQLEndpoint?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Import database field (df376030-46e9-4c77-bc05-debefc86e3d5).
            */
            ImportDatabase?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Import device field (1f14aa04-2868-481f-9247-30dc5c65672c).
            */
            ImportDevice?: {
                jsonValue: ItemExt
            };

            /**
            * Represents the Import language field (04e6b1f3-ae47-4d95-a154-2271075869a9).
            */
            ImportLanguage?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Import user field (f87f0d81-c32c-4c1d-8caf-67856c3ab06e).
            */
            ImportUser?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Layout folder template field (466902a9-6b16-41b1-9d33-7c55094a2713).
            */
            LayoutFolderTemplate?: {
                jsonValue: ItemExt
            };

            /**
            * Represents the Layout path field (c8d002f9-9518-4c5e-9baa-6617e13f0797).
            */
            LayoutPath?: {
                jsonValue: ItemExt
            };

            /**
            * Represents the Layout service configuration field (e3259313-387a-41f0-b113-962f14b1aa2b).
            */
            LayoutServiceConfiguration?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Layout template field (e13c1a83-9d60-4530-b318-3a5effcc6338).
            */
            LayoutTemplate?: {
                jsonValue: ItemExt
            };

            /**
            * Represents the Media Library folder template field (1cc82067-2b48-442a-a352-453d56a49d93).
            */
            MediaLibraryFolderTemplate?: {
                jsonValue: ItemExt
            };

            /**
            * Represents the App Name field (3e4f559f-8e59-4405-b50d-619811371f6c).
            */
            Name?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Optimize import indexing field (4088f63e-09e5-43fa-ae99-829bd9bdc114).
            */
            OptimizeImportIndexing?: {
                jsonValue: Field<boolean>
            };

            /**
            * Represents the Placeholder settings folder template field (f5594251-f757-429e-a9bd-07f65f6875b9).
            */
            PlaceholderSettingsFolderTemplate?: {
                jsonValue: ItemExt
            };

            /**
            * Represents the Placeholders path field (5ca117eb-8782-4a4f-9f2f-30de31fc2e34).
            */
            PlaceholdersPath?: {
                jsonValue: ItemExt
            };

            /**
            * Represents the Protect developer items field (b0711df7-724a-4c6c-8d4d-be846de6124c).
            */
            ProtectDeveloperItems?: {
                jsonValue: Field<boolean>
            };

            /**
            * Represents the Renderings folder template field (f5821c4c-226e-4953-8213-c0243826f85f).
            */
            RenderingsFolderTemplate?: {
                jsonValue: ItemExt
            };

            /**
            * Represents the Renderings path field (f29428d5-1285-48b8-a884-44057965829a).
            */
            RenderingsPath?: {
                jsonValue: ItemExt
            };

            /**
            * Represents the Route base template field (396af2f6-fe48-4fd4-a7e2-3da13ef977eb).
            */
            RouteBaseTemplate?: {
                jsonValue: ItemExt
            };

            /**
            * Represents the Route data sources path field (414f61dd-02c2-47d1-ba83-dcfbc3071e52).
            */
            RouteDatasourcesPath?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Route template name field (300fb7a0-b27f-44dd-9af0-b37a19723e0e).
            */
            RouteTemplateName?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Server Bundle field (4a3eeba3-a250-44f4-bd97-6e863cc6f0d5).
            */
            ServerBundle?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Server side rendering engine field (9016141c-ff51-40f2-9135-40f5161b9784).
            */
            ServerSideRenderingEngine?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the ServerSideRenderingEngineApplicationUrl field (5e8ed724-126a-4bb7-8106-85c2d1042c9e).
            */
            ServerSideRenderingEngineApplicationUrl?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the ServerSideRenderingEngineEditOnly field (557d5f36-6f2d-4eb6-a8ce-25f30f7b9397).
            */
            ServerSideRenderingEngineEditOnly?: {
                jsonValue: Field<boolean>
            };

            /**
            * Represents the Server side rendering engine endpoint URL field (89849738-34ee-46bc-b525-825f1153189e).
            */
            ServerSideRenderingEngineEndpointUrl?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Server side rendering function name field (7975673a-aafd-4c5b-96a5-cbcaac500a44).
            */
            ServerSideRenderingFunctionName?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Server side rendering worker processes field (6224a1ce-d964-4ee8-8e09-ad2f81e0a2b6).
            */
            ServerSideRenderingWorkerProcesses?: {
                jsonValue: Field<number>
            };

            /**
            * Represents the Template folder template field (218760c0-8001-4c2d-a8b0-61c128276f96).
            */
            TemplateFolderTemplate?: {
                jsonValue: ItemExt
            };

            /**
            * Represents the Use language specific layout field (1864e99d-c29a-40bf-96e0-b3e7896a013b).
            */
            UseLanguageSpecificLayout?: {
                jsonValue: Field<boolean>
            };


    }

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Multisite/JSS Site Folder
    */
    export type JssSiteFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Multisite/JSS Site Folder
    */
    export type JssSiteFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Multisite/JSS Site Grouping
    */
    export type JssSiteGrouping =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Multisite/JSS Site Grouping
    */
    export type JssSiteGroupingJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Multisite/JSS Tenant Folder
    */
    export type JssTenantFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Multisite/JSS Tenant Folder
    */
    export type JssTenantFolderJson =  {
        

    }
}
export namespace Presentation {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Presentation/Page Design
    */
    export type PageDesign =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Presentation/Page Design
    */
    export type PageDesignJson =  {
        

    }
}
export namespace Presentation.Folders {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Presentation/Folders/Page Design Folder
    */
    export type PageDesignFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Presentation/Folders/Page Design Folder
    */
    export type PageDesignFolderJson =  {
        

    }
}
export namespace Presentation {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Presentation/Page Designs
    */
    export type PageDesigns =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Presentation/Page Designs
    */
    export type PageDesignsJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Presentation/Partial Design
    */
    export type PartialDesign =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Presentation/Partial Design
    */
    export type PartialDesignJson =  {
        

    }
}
export namespace Presentation.Folders {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Presentation/Folders/Partial Design Folder
    */
    export type PartialDesignFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Presentation/Folders/Partial Design Folder
    */
    export type PartialDesignFolderJson =  {
        

    }
}
export namespace Presentation {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Presentation/Partial Designs
    */
    export type PartialDesigns =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Presentation/Partial Designs
    */
    export type PartialDesignsJson =  {
        

    }
}
export namespace PlaceholderSettings {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Placeholder Settings/Placeholder
    */
    export type Placeholder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Placeholder Settings/Placeholder
    */
    export type PlaceholderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Placeholder Settings/Placeholder Settings Folder
    */
    export type PlaceholderSettingsFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Placeholder Settings/Placeholder Settings Folder
    */
    export type PlaceholderSettingsFolderJson =  {
        

    }
}
export namespace Scaffolding.Actions.Site {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Actions/Site/PostDeleteStep
    */
    export type PostDeleteStep =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Actions/Site/PostDeleteStep
    */
    export type PostDeleteStepJson =  {
        

    }
}
export namespace Scaffolding.Actions.Tenant {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Actions/Tenant/PostDeleteStep
    */
    export type PostDeleteStep =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Actions/Tenant/PostDeleteStep
    */
    export type PostDeleteStepJson =  {
        

    }
}
export namespace Scaffolding.Actions.Site {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Actions/Site/PostSetupStep
    */
    export type PostSetupStep =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Actions/Site/PostSetupStep
    */
    export type PostSetupStepJson =  {
        

    }
}
export namespace Scaffolding.Actions.Tenant {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Actions/Tenant/PostSetupStep
    */
    export type PostSetupStep =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Actions/Tenant/PostSetupStep
    */
    export type PostSetupStepJson =  {
        

    }
}
export namespace Scaffolding.Actions.Site {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Actions/Site/PreDeleteStep
    */
    export type PreDeleteStep =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Actions/Site/PreDeleteStep
    */
    export type PreDeleteStepJson =  {
        

    }
}
export namespace Scaffolding.Actions.Tenant {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Actions/Tenant/PreDeleteStep
    */
    export type PreDeleteStep =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Actions/Tenant/PreDeleteStep
    */
    export type PreDeleteStepJson =  {
        

    }
}
export namespace Scaffolding.Actions.Site {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Actions/Site/PreDeleteValidationStep
    */
    export type PreDeleteValidationStep =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Actions/Site/PreDeleteValidationStep
    */
    export type PreDeleteValidationStepJson =  {
        

    }
}
export namespace Scaffolding.Actions.Tenant {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Actions/Tenant/PreDeleteValidationStep
    */
    export type PreDeleteValidationStep =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Actions/Tenant/PreDeleteValidationStep
    */
    export type PreDeleteValidationStepJson =  {
        

    }
}
export namespace Presentation {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Presentation/Presentation
    */
    export type Presentation =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Presentation/Presentation
    */
    export type PresentationJson =  {
        

    }
}
export namespace Scaffolding {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/RenderingHost
    */
    export type RenderingHost =  {
        fields?: { 
            /**
            * Represents the Application name field (3121c257-53cf-464a-b736-98b418876057).
            */
            AppName?: Field<string>;

            /**
            * Represents the Server side rendering engine application URL field (e32c1801-79b3-4fc1-a9c4-3c6e6c2968ae).
            */
            ServerSideRenderingEngineApplicationUrl?: Field<string>;

            /**
            * Represents the Server side rendering engine endpoint URL field (fc76919b-0d7c-4732-865d-2af795fb38a4).
            */
            ServerSideRenderingEngineEndpointUrl?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/RenderingHost
    */
    export type RenderingHostJson =  {
        
            /**
            * Represents the Application name field (3121c257-53cf-464a-b736-98b418876057).
            */
            AppName?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Server side rendering engine application URL field (e32c1801-79b3-4fc1-a9c4-3c6e6c2968ae).
            */
            ServerSideRenderingEngineApplicationUrl?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Server side rendering engine endpoint URL field (fc76919b-0d7c-4732-865d-2af795fb38a4).
            */
            ServerSideRenderingEngineEndpointUrl?: {
                jsonValue: Field<string>
            };


    }
}
export namespace Presentation {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Presentation/SXA JSS Layout
    */
    export type SxaJssLayout =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Presentation/SXA JSS Layout
    */
    export type SxaJssLayoutJson =  {
        

    }
}
export namespace Multisite {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Multisite/Shared Sites Settings
    */
    export type SharedSitesSettings =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Multisite/Shared Sites Settings
    */
    export type SharedSitesSettingsJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Multisite/Site
    */
    export type Site =  {
        fields?: { 
            /**
            * Represents the Predefined application rendering host field (f57099a3-526a-49f2-aebd-635453e48875).
            */
            RenderingHost?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Multisite/Site
    */
    export type SiteJson =  {
        
            /**
            * Represents the Predefined application rendering host field (f57099a3-526a-49f2-aebd-635453e48875).
            */
            RenderingHost?: {
                jsonValue: Field<string>
            };


    }
}
export namespace SiteMetadata {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/SiteMetadata/Sitemap Settings
    */
    export type SitemapSettings =  {
        fields?: { 
            /**
            * Represents the Generate sitemap media items field (7f070bc5-5cd4-474f-aa2f-ab2a0a128f00).
            */
            GenerateSitemapMediaItems?: Field<boolean>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/SiteMetadata/Sitemap Settings
    */
    export type SitemapSettingsJson =  {
        
            /**
            * Represents the Generate sitemap media items field (7f070bc5-5cd4-474f-aa2f-ab2a0a128f00).
            */
            GenerateSitemapMediaItems?: {
                jsonValue: Field<boolean>
            };


    }
}
export namespace Scaffolding {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Solution template
    */
    export type SolutionTemplate =  {
        fields?: { 
            /**
            * Represents the Enabled field (0d21f818-1938-4cd8-b0a8-a44f73d69367).
            */
            Enabled?: Field<boolean>;

            /**
            * Represents the Name field (82e64b52-0b8a-4a38-8c78-530c5493814e).
            */
            Name?: Field<string>;

            /**
            * Represents the Site Modules field (c262443b-653d-461d-96c8-7cfaa0ef2b2d).
            */
            "Site Modules"?: ItemExt[];

            /**
            * Represents the Tenant Modules field (41ac536a-923a-43f9-ac87-f3993f638125).
            */
            "Tenant Modules"?: ItemExt[];
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Solution template
    */
    export type SolutionTemplateJson =  {
        
            /**
            * Represents the Enabled field (0d21f818-1938-4cd8-b0a8-a44f73d69367).
            */
            Enabled?: {
                jsonValue: Field<boolean>
            };

            /**
            * Represents the Name field (82e64b52-0b8a-4a38-8c78-530c5493814e).
            */
            Name?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Site Modules field (c262443b-653d-461d-96c8-7cfaa0ef2b2d).
            */
            "Site Modules"?: {
                jsonValue: ItemExt[]
            };

            /**
            * Represents the Tenant Modules field (41ac536a-923a-43f9-ac87-f3993f638125).
            */
            "Tenant Modules"?: {
                jsonValue: ItemExt[]
            };


    }
}
export namespace HeadlessVariants {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Headless Variants/Variant Definition
    */
    export type VariantDefinition =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Headless Variants/Variant Definition
    */
    export type VariantDefinitionJson =  {
        

    }
}
export namespace Multisite.Base {

    /**
    * Represents the template /sitecore/templates/Foundation/JSS Experience Accelerator/Multisite/Base/_Base JSS Tenant
    */
    export type BaseJssTenant =  {
        fields?: { 
            /**
            * Represents the PlaceholderSettingsFolder field (102b58da-2a86-4953-b3cd-c9f91256b657).
            */
            PlaceholderSettingsFolder?: ItemExt;

            /**
            * Represents the Renderings location field (853b245f-53e4-4ebe-bab5-299f9de314b6).
            */
            RenderingsFolder?: ItemExt;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/JSS Experience Accelerator/Multisite/Base/_Base JSS Tenant
    */
    export type BaseJssTenantJson =  {
        
            /**
            * Represents the PlaceholderSettingsFolder field (102b58da-2a86-4953-b3cd-c9f91256b657).
            */
            PlaceholderSettingsFolder?: {
                jsonValue: ItemExt
            };

            /**
            * Represents the Renderings location field (853b245f-53e4-4ebe-bab5-299f9de314b6).
            */
            RenderingsFolder?: {
                jsonValue: ItemExt
            };


    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace Scaffolding.Actions.Site.Constants {

    export const AddItem = {
        TemplateId: "3aea335c-d06d-45b1-841a-cbc8d2d1ce40",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Scaffolding.Actions.Tenant.Constants {

    export const AddItem = {
        TemplateId: "1e1b739e-c378-4909-941d-171aca7362e5",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Presentation.AvailableRenderings.Constants {

    export const AvailableRenderingsFolder = {
        TemplateId: "26ec1d18-11b2-4dd9-8326-f6115f4fd7eb",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Multisite.Constants {

    export const BasePage = {
        TemplateId: "47151711-26ca-434e-8132-d3e0b7d26683",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Presentation.RenderingParameters.Constants {

    export const BaseRenderingParameters = {
        TemplateId: "4247aad4-ebde-4994-998f-e067a51b1fe4",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Scaffolding.Actions.Site.Constants {

    export const EditSiteItem = {
        TemplateId: "f040db03-87fe-4e10-ae40-53c63175e31b",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Scaffolding.Actions.Tenant.Constants {

    export const EditTenantTemplate = {
        TemplateId: "88752f77-9109-424c-b1d8-af91e6369a2e",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Scaffolding.Actions.Site.Constants {

    export const ExecuteScript = {
        TemplateId: "bc9bb684-36df-4285-888b-d8b4d87b10de",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Scaffolding.Actions.Tenant.Constants {

    export const ExecuteScript = {
        TemplateId: "3a385b25-df9b-47ac-9f6b-39c8534e81f1",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Multisite.Constants {

    export const HeadlessSite = {
        TemplateId: "9ed66404-64c9-4122-90e1-869cb3cea566",
    
        BaseTemplateIds: [
        ]
    }
    export const HeadlessTenant = {
        TemplateId: "b91811f1-fa8b-47f8-b131-bd2c6d5ec805",
    
        BaseTemplateIds: [
            "053e9155-3993-42f3-9182-5854dc5355b3", 
        ]
    }
}
export namespace Scaffolding.Roots.Constants {

    export const HeadlessSiteSetupRoot = {
        TemplateId: "bed31d6f-d968-45a9-b54e-12d7f977d861",
    
        BaseTemplateIds: [
        ]
    }
    export const HeadlessTenantSetupRoot = {
        TemplateId: "f036b5e0-37fb-4537-9d36-ef84e5bd41b7",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace HeadlessVariants.Constants {

    export const HeadlessVariants = {
        TemplateId: "49c111d0-6867-4798-a724-1f103166e6e9",
    
        BaseTemplateIds: [
        ]
    }
    export const HeadlessVariantsGrouping = {
        TemplateId: "da26c636-96e1-45e4-88d6-3fcec70d5699",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Scaffolding.Actions.Site.Constants {

    export const InputValidationStep = {
        TemplateId: "9eded2f7-f847-4893-8a0b-f69e7fcf3593",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Scaffolding.Actions.Tenant.Constants {

    export const InputValidationStep = {
        TemplateId: "d028fef2-babf-4ad1-bbe7-4d62a977992f",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Multisite.Constants {

    export const JssData = {
        TemplateId: "a29d272e-9d48-453c-9e9d-b47585fa7f20",
    
        BaseTemplateIds: [
        ]
    }
    export const JssSettings = {
        TemplateId: "ec848505-d30c-4bdc-a0aa-7cc9d320085e",
    
        BaseTemplateIds: [
        ]
    }
    export const JssSiteFolder = {
        TemplateId: "ce91fbd6-4d89-42c9-b5bc-2a670439e1ff",
    
        BaseTemplateIds: [
        ]
    }
    export const JssSiteGrouping = {
        TemplateId: "8357f958-9aaa-46db-8898-36448a96356f",
    
        BaseTemplateIds: [
        ]
    }
    export const JssTenantFolder = {
        TemplateId: "ca170f6f-5ec2-4e0c-b4bb-c77b7931b168",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Presentation.Constants {

    export const PageDesign = {
        TemplateId: "1105b8f8-1e00-426b-bf1f-c840742d827b",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Presentation.Folders.Constants {

    export const PageDesignFolder = {
        TemplateId: "023f5d48-979d-4381-bc5e-149e36abd3bd",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Presentation.Constants {

    export const PageDesigns = {
        TemplateId: "daaf41fd-96db-4892-be99-f62f16d036c4",
    
        BaseTemplateIds: [
        ]
    }
    export const PartialDesign = {
        TemplateId: "fd2059fd-6043-4dfe-8c04-e2437ce87634",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Presentation.Folders.Constants {

    export const PartialDesignFolder = {
        TemplateId: "25f01f50-5534-44f9-b1ba-bcbb60b2d13d",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Presentation.Constants {

    export const PartialDesigns = {
        TemplateId: "79c9fa01-5f6a-48b2-b459-05bbaa826a9d",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace PlaceholderSettings.Constants {

    export const Placeholder = {
        TemplateId: "d2a6884c-04d5-4089-a64e-d27ca9d68d4c",
    
        BaseTemplateIds: [
        ]
    }
    export const PlaceholderSettingsFolder = {
        TemplateId: "52288e39-7830-4694-b62d-32a54c6ef7ba",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Scaffolding.Actions.Site.Constants {

    export const PostDeleteStep = {
        TemplateId: "b2085789-5385-4138-83f0-96f3767cb156",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Scaffolding.Actions.Tenant.Constants {

    export const PostDeleteStep = {
        TemplateId: "78d6ec9b-66e3-4763-9870-03cf314ee37a",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Scaffolding.Actions.Site.Constants {

    export const PostSetupStep = {
        TemplateId: "8ff2febf-f6d2-461d-9ed3-8b0cb5d9d86f",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Scaffolding.Actions.Tenant.Constants {

    export const PostSetupStep = {
        TemplateId: "0c602893-2be9-4020-912d-56af21deff73",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Scaffolding.Actions.Site.Constants {

    export const PreDeleteStep = {
        TemplateId: "52510f54-9ec5-464c-b075-ef44b5c2f96b",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Scaffolding.Actions.Tenant.Constants {

    export const PreDeleteStep = {
        TemplateId: "adb13651-2eb9-494f-ada0-0dfda0b2ebbf",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Scaffolding.Actions.Site.Constants {

    export const PreDeleteValidationStep = {
        TemplateId: "408fd8ab-1667-440b-a605-1370ddf0a51f",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Scaffolding.Actions.Tenant.Constants {

    export const PreDeleteValidationStep = {
        TemplateId: "edf1fa42-06c4-4703-ab1a-f23495bc6d8f",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Presentation.Constants {

    export const Presentation = {
        TemplateId: "0a70fa73-8923-4a6e-abf3-4134f25f3221",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Scaffolding.Constants {

    export const RenderingHost = {
        TemplateId: "bc71d442-3e4f-46ba-887c-746e54f9bb83",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Presentation.Constants {

    export const SxaJssLayout = {
        TemplateId: "e4e11508-04a4-4b0b-a263-5201f811c9cd",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Multisite.Constants {

    export const SharedSitesSettings = {
        TemplateId: "c14bf746-030f-4e59-8594-395f6d299e61",
    
        BaseTemplateIds: [
        ]
    }
    export const Site = {
        TemplateId: "e46f3af2-39fa-4866-a157-7017c4b2a40c",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace SiteMetadata.Constants {

    export const SitemapSettings = {
        TemplateId: "c71d8566-35c8-49b7-a84d-9d176e9cbd05",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Scaffolding.Constants {

    export const SolutionTemplate = {
        TemplateId: "1b2dfd3b-f2f2-4f40-a75c-f6c2490919c4",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace HeadlessVariants.Constants {

    export const VariantDefinition = {
        TemplateId: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Multisite.Base.Constants {

    export const BaseJssTenant = {
        TemplateId: "053e9155-3993-42f3-9182-5854dc5355b3",
    
        BaseTemplateIds: [
        ]
    }
}    


