
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { ItemExt } from '../lib/_.Sitecore.Override'
// @ts-ignore 
import { Field, ImageField, FileField, LinkField } from '@sitecore-jss/sitecore-jss-nextjs';
// @ts-ignore 
import { ComponentProps } from '../lib/component-props';
// @ts-ignore 
import { Base as FoundationSugconBase } from "./Foundation.Sugcon.model"
// @ts-ignore 
import { Utility as FoundationSugconUtility } from "./Foundation.Sugcon.model"

export namespace Base {

    /**
    * Class to wrap the rendering parameter /sitecore/templates/Foundation/SUGCON/Base/_Base Rendering Params
    * This will automatically parse the string rendering parameters into the appropriate types (where possible)
    */
    export class BaseRenderingParamsClass  {
            constructor(public params: Record<string, string>) {
                
            }
        
    }
}
export namespace Utility {

    /**
    * Represents the template /sitecore/templates/Foundation/SUGCON/Utility/_RenderWithChildren
    */
    export type RenderWithChildren =  {
        fields?: { 
            /**
            * Child items
            */
            children : ItemExt[];
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/SUGCON/Utility/_RenderWithChildren
    */
    export type RenderWithChildrenJson =  {
        
            /**
            * Child items
            */
            children : ItemExt[];


    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace Base.Constants {

    export const BaseRenderingParams = {
        TemplateId: "0cd007dd-b31d-4e56-91d7-fbd7d55330b3",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Utility.Constants {

    export const RenderWithChildren = {
        TemplateId: "75848221-862f-48ed-83d1-af13ed1c2cd7",
    
        BaseTemplateIds: [
        ]
    }
}    


