
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { ItemExt } from '../lib/_.Sitecore.Override'
// @ts-ignore 
import { Field, ImageField, FileField, LinkField } from '@sitecore-jss/sitecore-jss-nextjs';
// @ts-ignore 
import { ComponentProps } from '../lib/component-props';
// @ts-ignore 
import { Project as ProjectSugconProject } from "./Project.Sugcon.model"
// @ts-ignore 
import { Multisite as FoundationJssExperienceAcceleratorMultisite } from "./Foundation.JssExperienceAccelerator.model"
// @ts-ignore 
import { Presentation as FoundationJssExperienceAcceleratorPresentation } from "./Foundation.JssExperienceAccelerator.model"

export namespace Project.Sugcon {

    /**
    * Represents the template /sitecore/templates/Project/SUGCON/Headless Site
    */
    export type HeadlessSite = FoundationJssExperienceAcceleratorMultisite.HeadlessSite &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/SUGCON/Headless Site
    */
    export type HeadlessSiteJson = FoundationJssExperienceAcceleratorMultisite.HeadlessSiteJson &  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/SUGCON/Headless Tenant
    */
    export type HeadlessTenant = FoundationJssExperienceAcceleratorMultisite.HeadlessTenant &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/SUGCON/Headless Tenant
    */
    export type HeadlessTenantJson = FoundationJssExperienceAcceleratorMultisite.HeadlessTenantJson &  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/SUGCON/JSS Settings
    */
    export type JssSettings = FoundationJssExperienceAcceleratorMultisite.JssSettings &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/SUGCON/JSS Settings
    */
    export type JssSettingsJson = FoundationJssExperienceAcceleratorMultisite.JssSettingsJson &  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/SUGCON/Page Design Folder
    */
    export type PageDesignFolder = FoundationJssExperienceAcceleratorPresentation.Folders.PageDesignFolder &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/SUGCON/Page Design Folder
    */
    export type PageDesignFolderJson = FoundationJssExperienceAcceleratorPresentation.Folders.PageDesignFolderJson &  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/SUGCON/Page Designs
    */
    export type PageDesigns = FoundationJssExperienceAcceleratorPresentation.PageDesigns &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/SUGCON/Page Designs
    */
    export type PageDesignsJson = FoundationJssExperienceAcceleratorPresentation.PageDesignsJson &  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/SUGCON/Partial Design Folder
    */
    export type PartialDesignFolder = FoundationJssExperienceAcceleratorPresentation.Folders.PartialDesignFolder &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/SUGCON/Partial Design Folder
    */
    export type PartialDesignFolderJson = FoundationJssExperienceAcceleratorPresentation.Folders.PartialDesignFolderJson &  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/SUGCON/Partial Designs
    */
    export type PartialDesigns = FoundationJssExperienceAcceleratorPresentation.PartialDesigns &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/SUGCON/Partial Designs
    */
    export type PartialDesignsJson = FoundationJssExperienceAcceleratorPresentation.PartialDesignsJson &  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/SUGCON/Sugcon Page
    */
    export type SugconPage = FoundationJssExperienceAcceleratorMultisite.BasePage &  {
        fields?: { 
            /**
            * Represents the Content field (1bd4f07a-dfa4-463d-b01b-f9c13ff596fd).
            */
            Content?: Field<string>;

            /**
            * Represents the Title field (4da86130-8d6b-4d4f-8e61-3426ab49905d).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/SUGCON/Sugcon Page
    */
    export type SugconPageJson = FoundationJssExperienceAcceleratorMultisite.BasePageJson &  {
        
            /**
            * Represents the Content field (1bd4f07a-dfa4-463d-b01b-f9c13ff596fd).
            */
            Content?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Title field (4da86130-8d6b-4d4f-8e61-3426ab49905d).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }
}


