
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { ItemExt } from '../lib/_.Sitecore.Override'
// @ts-ignore 
import { Field, ImageField, FileField, LinkField } from '@sitecore-jss/sitecore-jss-nextjs';
// @ts-ignore 
import { ComponentProps } from '../lib/component-props';
// @ts-ignore 
import { Project as ProjectSugconProject } from "./Project.Sugcon.model"
// @ts-ignore 
import { Multisite as FoundationJssExperienceAcceleratorMultisite } from "./Foundation.JssExperienceAccelerator.model"
// @ts-ignore 
import { Presentation as FoundationJssExperienceAcceleratorPresentation } from "./Foundation.JssExperienceAccelerator.model"

export namespace Project.Sugcon {

    /**
    * Represents the template /sitecore/templates/Project/SUGCON/Headless Site
    */
    export type HeadlessSite = FoundationJssExperienceAcceleratorMultisite.HeadlessSite &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/SUGCON/Headless Site
    */
    export type HeadlessSiteJson = FoundationJssExperienceAcceleratorMultisite.HeadlessSiteJson &  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/SUGCON/Headless Tenant
    */
    export type HeadlessTenant = FoundationJssExperienceAcceleratorMultisite.HeadlessTenant &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/SUGCON/Headless Tenant
    */
    export type HeadlessTenantJson = FoundationJssExperienceAcceleratorMultisite.HeadlessTenantJson &  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/SUGCON/JSS Settings
    */
    export type JssSettings = FoundationJssExperienceAcceleratorMultisite.JssSettings &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/SUGCON/JSS Settings
    */
    export type JssSettingsJson = FoundationJssExperienceAcceleratorMultisite.JssSettingsJson &  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/SUGCON/Page Design Folder
    */
    export type PageDesignFolder = FoundationJssExperienceAcceleratorPresentation.Folders.PageDesignFolder &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/SUGCON/Page Design Folder
    */
    export type PageDesignFolderJson = FoundationJssExperienceAcceleratorPresentation.Folders.PageDesignFolderJson &  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/SUGCON/Page Designs
    */
    export type PageDesigns = FoundationJssExperienceAcceleratorPresentation.PageDesigns &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/SUGCON/Page Designs
    */
    export type PageDesignsJson = FoundationJssExperienceAcceleratorPresentation.PageDesignsJson &  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/SUGCON/Partial Design Folder
    */
    export type PartialDesignFolder = FoundationJssExperienceAcceleratorPresentation.Folders.PartialDesignFolder &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/SUGCON/Partial Design Folder
    */
    export type PartialDesignFolderJson = FoundationJssExperienceAcceleratorPresentation.Folders.PartialDesignFolderJson &  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/SUGCON/Partial Designs
    */
    export type PartialDesigns = FoundationJssExperienceAcceleratorPresentation.PartialDesigns &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/SUGCON/Partial Designs
    */
    export type PartialDesignsJson = FoundationJssExperienceAcceleratorPresentation.PartialDesignsJson &  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/SUGCON/Sugcon Page
    */
    export type SugconPage = FoundationJssExperienceAcceleratorMultisite.BasePage &  {
        fields?: { 
            /**
            * Represents the Content field (1bd4f07a-dfa4-463d-b01b-f9c13ff596fd).
            */
            Content?: Field<string>;

            /**
            * Represents the Title field (4da86130-8d6b-4d4f-8e61-3426ab49905d).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/SUGCON/Sugcon Page
    */
    export type SugconPageJson = FoundationJssExperienceAcceleratorMultisite.BasePageJson &  {
        
            /**
            * Represents the Content field (1bd4f07a-dfa4-463d-b01b-f9c13ff596fd).
            */
            Content?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Title field (4da86130-8d6b-4d4f-8e61-3426ab49905d).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace Project.Sugcon.Constants {

    export const HeadlessSite = {
        TemplateId: "0b72bf90-867b-421f-806f-34f5ee4e9c85",
    
        BaseTemplateIds: [
            "9ed66404-64c9-4122-90e1-869cb3cea566", 
        ]
    }
    export const HeadlessTenant = {
        TemplateId: "66377999-0398-449b-bbec-4886a0fe5703",
    
        BaseTemplateIds: [
            "b91811f1-fa8b-47f8-b131-bd2c6d5ec805", 
            "053e9155-3993-42f3-9182-5854dc5355b3", 
        ]
    }
    export const JssSettings = {
        TemplateId: "7d3c4134-cb52-4dd8-931c-e3ef741f12a4",
    
        BaseTemplateIds: [
            "ec848505-d30c-4bdc-a0aa-7cc9d320085e", 
        ]
    }
    export const PageDesignFolder = {
        TemplateId: "38e4778c-018f-4c25-b0d3-a8696bfbc1ec",
    
        BaseTemplateIds: [
            "023f5d48-979d-4381-bc5e-149e36abd3bd", 
        ]
    }
    export const PageDesigns = {
        TemplateId: "99977167-f6ec-4dcb-b179-39065e1e59c6",
    
        BaseTemplateIds: [
            "daaf41fd-96db-4892-be99-f62f16d036c4", 
        ]
    }
    export const PartialDesignFolder = {
        TemplateId: "1ff41e39-e31b-4c48-957b-9be8cfd8471b",
    
        BaseTemplateIds: [
            "25f01f50-5534-44f9-b1ba-bcbb60b2d13d", 
        ]
    }
    export const PartialDesigns = {
        TemplateId: "025bdd7b-554a-4b93-a30b-b83a6b5894a0",
    
        BaseTemplateIds: [
            "79c9fa01-5f6a-48b2-b459-05bbaa826a9d", 
        ]
    }
    export const SugconPage = {
        TemplateId: "4a51367f-bff4-4468-93c0-9227ae60c4a5",
    
        BaseTemplateIds: [
            "47151711-26ca-434e-8132-d3e0b7d26683", 
        ]
    }
}    


